### ISSUE TITLE
Recherche de podcast

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#10]
Ajouter uhamp de recherche où on pourrait mettre des mots clefs et rechercher dans les contenus d’articles.

**Comment by iLandes** [comment]
Pour le moment dans la Build 6 implémentation d'une barre de recherche qui permet de filtrer sur le titre.

En ce qui concerne des recherches plus approfondies et avant de réécrire google, je pense qu'il faut attendre un retour des utilisateurs pour voir les recherches qu'ils souhaitent faire.

**Comment by DVRGV38** [comment]
Changer "Clear text" en "Effacer"

**Comment by iLandes** [comment]
C'est difficile a trouver comment changer ce bouton mais je cherche…

**Comment by iLandes** [comment]
C'est trouvé. Grace à la communauté cococafe. 

Ce serais aussi sympa de les citer dans les remerciements c'est un aussi un peu grâce à eux que l'on s'est rencontré

**Comment by DVRGV38** [comment]
Je suis d’accord.
On peut les rajouter dans les remerciements.
