### ISSUE TITLE
Panne signalée à partir de la Build-3

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#11]
Panne lors des tests du build 3. Besoins d'informations

**Comment by DVRGV38** [comment]
Pas de soucis pour moi concernant la panne pour le lecteur... Le bouton s'appelle "Play" si on peut le changer en "Lecture" c'est un petit détail insignifiant...
De plus, les infos de la barre d'état lorsque l'application est lancée, sont toutes en anglais... La batterie, l'heure... Sinon, RAS

**Comment by iLandes** [comment]
Il y eu aussi un plantage dans la build 4. Si vous pouvez me dire à quoi c'est dû.

En ce qui concerne les informations batterie et heure je pense que cela vient de TestFlight, les développer n'ont pas la main la dessus.

Pour le bouton play je créé un nouveau fil.

Il faut que je teste plus en profondeur le lecteur audio. Si vous avez des informations sur le plantage que je puisse le reproduire, je suis preneur.

**Comment by iLandes** [comment]
Apparement cela c'est produit le 15 Juillet des infos ?

**Comment by DVRGV38** [comment]
Je ne me souviens pas…
Mais de ce dont je me rappelle, c’est un soucis avec le menu, j’ai dû cliquer plusieurs fois pour afficher les choix… Mais je n’ai pas eu ce petit bug à nouveau par la suite.

**Comment by iLandes** [comment]
ok, je viens de réécrire le lecteur de podcast avec un code plus moderne. je ferme cette issue pour le moment
