### ISSUE TITLE
Affichage du résumé

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#12]
L'affichage du résumé ne laisse pas apparaitre le haut du texte.

**Comment by DVRGV38** [comment]
Ne peut-on pas concaténé #titre#&"par "&#auteur#&" le "#Date#&#résum"# ?

**Comment by iLandes** [comment]
Ok, je regarde ça

**Comment by iLandes** [comment]
Résolu dans le build 4
