### ISSUE TITLE
Affichage détail du podcast

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#16]
L'affichage du détail du podcast ne se fait pas correctement lorsque le texte est long, le texte est parfois tronqué. Le texte est calé en bas au lieu d'en haut.

**Comment by DVRGV38** [comment]
Peut-être pourrais-tu donc créer une sous-page avec les infos du podcasts, car il y aura l'affichage des commentaires après, et afficher le lecteur en cliquant sur un bouton dédié...

**Comment by iLandes** [comment]
Je pense faire l'inverse. Laisser le podcast accessible sur cette page. Il commence à ce charger dès qu'on arrive sur cette page. Par contre je rajouterais par la suite un accès aux commentaires à partir de cette page.

En effet je pense que l'utilisateur souhaite en premier lieu écouter le podcast puis ensuite lire / rédiger un commentaire. 

J'ouvre un nouveau post pour cette évolution. Je laisse celui là ouvert car j'ai un bug d'affichage quand le texte est trop long.

**Comment by iLandes** [comment]
Corrigé dans la build 6

**Comment by DVRGV38** [comment]
Mettre le titre de l'article en "entête" comme sur la page principale "Tous les podcasts....."
Les images des articles ne sont pas affichés, est-ce normal, peut-être pas possible à récupérer... ?

**Comment by iLandes** [comment]
Là c'est moi qui vais paraitre chiant mais ce n'est pas trop naturel pour le coup surtout sur les petits devices. Je pense qu'il faut mieux réserver la zone du haut pour les futurs bouton partager, sauvegarder sur le device, commenter, noter etc.

Pour les images je crée un autre sujet sinon c'est confusant
