### ISSUE TITLE
Chargement des podcasts impossible -> Message

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#17]
Prévoir de prévenir l'utilisateur au cas où les podcasts ne sont pas accessibles.

**Comment by DVRGV38** [comment]
Et pourquoi pas mettre en cache les 5 derniers podcasts par exemple ou les 10 derniers...

**Comment by iLandes** [comment]
Pour la mise en cache j'ouvre un autre post.

Pour le problème concerné par ce post : A partir de la Build 6, affichage d'un waiting indicator dans detail.

A faire pour la liste : rafraîchissement de la liste

**Comment by iLandes** [comment]
Rafraîchissement de la liste des podcast disponible depuis la build 6
