### ISSUE TITLE
Commentaires sur les podcasts

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#18]
Pour gérer les commentaires sur les podcast il me faut l'adresse où récupérer les commentaires (GET) d'un podcast ainsi que l'adresse pour publier un commentaire (POST).

Je penses que tu veux récupérer / envoyer les commentaires directement sur le site dvrgv.org

**Comment by DVRGV38** [comment]
Excellente question !!!
Sous wordpress, j’ai aucune idée de la procédure à suivre…
Je sais qu’on peut afficher les commentaires via un flux xml, mais on ne peut pas y répondre…
Les commentaires sont affichés sur chaque page des articles contenant les podcasts…
En faisant du parsing, crois-tu que c’est envisageable,
Je vais me documenté sur google pour t’orienter !!!!

**Comment by iLandes** [comment]
Pour les récupérer y'a pas de problème je pense pour faire un parsing. Cela peut être une première étape.

Pour publier Firebase permet de faire cela dans une base de donnes JSon mais ce sera compliqué après de les intégrer dans wordpress.

A suivre…

**Comment by DVRGV38** [comment]
Ne peut ton pas publié directement dans la table de la base de donnée mysql de wordpress ?
Pour les récupérer, ce sera aussi plus simple…

**Comment by iLandes** [comment]
Je vais étudier cela plus en profondeur. Tu utilise quelle version de WordPress ?

**Comment by DVRGV38** [comment]
Il s’agit de la version 4.6 de Wordpress.
