### ISSUE TITLE
Orthographe

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#2]
dans la page du player, il y a 2 fautes de frappes : « Poadcast charger à XX% » : "Podcast chargé à XX% »

**Comment by iLandes** [comment]
Corriger, visible à partir du build 4

**Comment by DVRGV38** [comment]
Non corrigé dans le lecteur

**Comment by DVRGV38** [comment]
Non corrigé dans la dernière version : Poadcast

**Comment by iLandes** [comment]
Je pense avoir trouvé l'erreur à vérifier dans la Build 5
