### ISSUE TITLE
Vérifier que le serveur est accessible

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#20]
En cas de non disponibilité, afficher une boite de dialogue

**Comment by DVRGV38** [comment]
J'ai testé l'application quand les données étaient en train de migrer vers notre nouveau serveur... ça ne génère aucune erreur, la liste est juste vide.
Il faut donc, comme tu le dis, un message...

**Comment by iLandes** [comment]
Message ajouté dans la build 7
