### ISSUE TITLE
Illustration des podcasts

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#23]
Les images des articles ne sont pas affichées

**Comment by iLandes** [comment]
Je veux bien mais je ne trouve pas dans le flux XML de lien vers des images à part
https://www.dvrgv.org/LogosPartenaires/DVRGV-carre-1400x1400px.jpg 
Qui représente le logo de l'association 

D'ailleurs sur le site wordpress il n'y pas d'illustration pour les podcasts ou alors je n'ai pas trouvé

**Comment by DVRGV38** [comment]
Voilà pourquoi je pense que dans une prochaine version, il serait peut-être mieux de récupérer peut-être les articles via la BD ?
Qu’en penses-tu ?

**Comment by iLandes** [comment]
Cela pose un problème de sécurité à mon avis. Il est toujours plus lourd d'interroger une base de données qu'un flux xml. De plus cela pose aussi des problèmes de maintenance. Que sera passera-t-il à la prochaine mise à jour de wordpress ?

**Attention ici encore on s'éloigne du sujet de base**

Où sont stockées les images que tu veux utiliser pour les podcasts ?

**Comment by iLandes** [comment]
J'ai trouvé dans le flux de démo des liens vers des images comme celle la

http://test.dvrgv.org/PhotosArticles/2016-08-16-FR3AlpesStudio-Camera.jpg

Cette image fait 2,1 Mo. Ce n'est pas envisageable pour une application mobile. Il faudrait des images beaucoup plus petite pour conserver de la fluidité en 4g/3g/Edge et surtout ne pas bouffer tout le forfait internet des utilisateur mobile.

Peut-tu faire quelque chose.

**Comment by DVRGV38** [comment]
Oui, c'est le seul moyen que j'ai trouvé!

Envoyé de mon iPhone

**Comment by iLandes** [comment]
Transféré dans le GitHub prive
