### ISSUE TITLE
A propos

### ISSUE THREAD

**Issue by DVRGV38** [iLandes/DVRGV-PUBLIC#25]
En vue des autres onglets qui arriveront dans les prochaines versions, je suggère que les pages présentation et Remerciements, soient mises dans un seul onglet "A propos", on y rajouterait aussi, le numéro de la version de l'application.

**Comment by iLandes** [comment]
Je garde cela sous le coude. Pour l'instant je laisse comme tel. Je regrouperais lorsque'on aura besoin de plus de trois onglets.

**Comment by iLandes** [comment]
A faire : Mettre à jour le code HTML

**Comment by iLandes** [comment]
Le code HTML que tu m'as fournis n'est pas standardisé. Voici quelques règles à respecter :

- Le fichier doit contenir une entête pour préciser l'encodage utilisé du genre 
```
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
</head>
```

- L'extension du fichier doit être .html 
- Ne pas utiliser « et » mais le caractère " exemple : <A HREF = "http://www.dvrgv.org">
- Pas d'espace ni avant ni après une adresse html
- Le TARGET n'est pas obligatoire car j'ouvre chaque lien dans Safari par défaut

**Comment by DVRGV38** [comment]
Je te joins les fichiers au format HTML
