### ISSUE TITLE
Description HTML

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#26]
Quelque chose a changé dans le flux. La description contient maintenant des balises HTML. Ce n'est pas géré.

Merci de m'avertir quand tu veux changer des choses côté serveur sinon on n'arrivera jamais à sortir une V1

**Comment by DVRGV38** [comment]
Pas de solutions…
Mes articles étaient déjà en HTML, je pense que l’ancien gestionnaire de podcast  enlevait les balises…
Ce qui est très curieux aussi, c’est que les balises contenant l’appel aux images/photos n’apparaissent pas…
D’ailleurs pour infos, si tu peux faire un replace(), les balises qui s’affichent sont celles des liens ou des retours à la ligne, soit :<A HREF=«  »> et <BR/>
Ensuite le nom de ‘l’auteur de l’article n’apparaît plus non plus ;)
Encore une fois, je suis désolé.
Je ne touche plus au niveau du serveur, enfin tant qu’il n’y a pas d’autres problèmes...

**Comment by DVRGV38** [comment]
Je suis allé sur le forum de PowerPress pour avoir des informations, j’attends un retour utilisateur…
Si rien d’ici demain, je peux tout à fait remettre l’ancien gestionnaire de podcast. Mais nous n’aurons plus la durée…
A toi de me dire…

**Comment by DVRGV38** [comment]
J'ai remis l'ancien gestionnaire de podcast, le temps pour moi de trouver une solution. Ce qui te permettra de travailler en paix, sans subir mes erreurs ;)
Encore désolé...

**Comment by iLandes** [comment]
Laisse tomber je pense pouvoir me débrouiller pour décoder le HTML. Remet le nouveau gestionnaire de podacst s'il te plait

**Comment by DVRGV38** [comment]
PowerPress actif…
Je garde PodPress installé au cas où !!!

**Comment by iLandes** [comment]
Résolu dans la prochaine build. J'ai réussi à virer le code HTML...
