### ISSUE TITLE
Auteur du podcast

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#27]
Je ne sais pas ce qui c'est passé mais la balise dc:creator a disparu du podcast. Elle contenait l'auteur du podcast. J'utilise la balise iTunes:author à la place.

Dis moi si c'est correct pour toi

**Comment by DVRGV38** [comment]
Oui, c'est correct ! 
Du bon travail Monsieur Sèb, du bon travail !

Envoyé de mon iPhone
