### ISSUE TITLE
Version 1.0

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#28]
Repense qu'il est temps de quitter le mode béta et de soumettre la version 1.0 dans le store.

C'est le moment de savoir si notre application va être approuvé par Apple. On est jamais à l'abri d'une surprise.

Je pense que la build 8 est pas mal et dores et déjà présentable. Qu'en penses tu ?

**Comment by DVRGV38** [comment]
Je suis assez d'accord ! Peux-tu soumettre la version huit afin que je teste avant de la publier ? Dois-je rédigé un texte de présentation de l'application ? 

Envoyé de mon iPhone

**Comment by iLandes** [comment]
Il faut une : 

- description (max 4000 caractères)
- mot clés (max 100 caractères)
- une adresse url de référence (le site DVRGV)

**Comment by DVRGV38** [comment]
Description :
L’association DVRGV est heureuse de vous  présenter son application  dans sa première version.
Vous avez envie de voyager en restant là où vous êtes, de découvrir les choses sous un nouvel angle ?
L’application DVRGV est une extension de notre site Web, grâce à laquelle vous pourrez découvrir des ambiances sonores (Phonores) ou des reportages de haute qualité.
Devenez un DVRGViste en installant cette application et n’hésitez pas à nous faire remonter toutes suggestions pour notre prochaine version.

Mots clés :
Association, dvrgv, son, reportage, audio, ambiance, Relaxation, Découverte,

**Comment by iLandes** [comment]
Ok, c'est parti…
