### ISSUE TITLE
Logo sans DVRGV

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#29]
Tu pourrais m'envoyer le logo de l'association sans les lettres DVRGV. Je pense que pour l'icône de l'application ce sera mieux. Ce n'est pas très jolie d'avoir DVRGV inscrit deux fois l'un au dessus de l'autre. De plus sur les petits devices les lettres ne sont pas très visibles.

Merci

s
e
b

**Comment by DVRGV38** [comment]
Je ne crois pas que j’ai ça en magasin…
Je vais voir avec mon designer si peux me refaire ça...
