### ISSUE TITLE
Utilisation des liens HTML

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#30]
Les liens HTML ne semble pas fonctionner avec les fichiers Markdown

**Comment by DVRGV38** [comment]
Ok, quelle est donc l'alternative?

**Comment by iLandes** [comment]
Je vais creuser au niveau de l'API

**Comment by iLandes** [comment]
Rien à faire au niveau de l'API, le fichier Markdown est transformé en text et VoiceOver ne peut pas distinguer les liens dans le texte.

Je transforme le tout en mini navigateur internet dans la prochaine build, dis moi si c'est mieux pour toi. Je livre la build 9 ce soir (14/09)

**Comment by DVRGV38** [comment]
Oui, ce serait parfait…

**Comment by iLandes** [comment]
Ce bug est corrigé pour la build 10. J'ai aussi implémenter les liens disponibles dans la description des podcasts.
