### ISSUE TITLE
Site web de teste

### ISSUE THREAD

**Issue by DVRGV38** [iLandes/DVRGV-PUBLIC#31]
Ici l'adresse URL (non en ssl) qui permettra d'effectuer les testes.
http://test.dvrgv.org
Actuellement, j'ai modifié le site afin qu'il soit nettoyé des anciens plugins non utilisés dont PodPress l'ancien gestionnaire RSS de podcasts.
PowerPress étant complètement fonctionnel, les prochains podcasts seront ajouté avec ce gestionnaire, le flux xml n'est plus opérant avec l'application.
De plus, la balise image du podcast est remplit pour le dernier podcast avec une des photos de l'article, ce qui te permettra peut-être de l'afficher...
Je n'ai remplacé qu'un seul article car c'est la version de teste. Lorsque tu auras réglé ce problème, je pourrai basculé les modifications et modifier tous les articles  sur le site en production, en même temps que tu soumettras l'application chez Apple...

**Comment by iLandes** [comment]
Pour le moment il n'y a qu'un seul podcast dans le flux XML : Les coulisses d'un journal télévisé.

Il faudrait le compléter que je puisse faire des tests

**Comment by iLandes** [comment]
Implémenter dans la build 10
