### ISSUE TITLE
Langue de l'application

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#32]
Actuellement l'application est définie comme étant en langue anglaise. Modifier pour Français

**Comment by DVRGV38** [comment]
Je pense qu’il doit y avoir une constante non défini dans l’application, car même les infos de la barre d’état me sont énoncées en anglais…

**Comment by iLandes** [comment]
C'est exactement cela. Par défaut la langue native des apps est l'anglais. C'est corrigé pour le prochain build (9)
