### ISSUE TITLE
Retours utilisateurs Version 1.0

### ISSUE THREAD

**Issue by DVRGV38** [iLandes/DVRGV-PUBLIC#33]
Utilisateur 1: avec VoiceOver sur Iphone SE, iOs10

De mon côté il y a un petit souci, les boutons radios de la zone de recherche sont labelisés title pour les deux, et je ne vois pas de différence entre l'un et l'autre.

De plus le fait que le champ de recherche soit actif par défaut empèche la vue des onglets en bas Impossible de quitter le clavier, un bouton terminer au lieu de rechercher serait peut-être plus aproprié et un bouton de recherche juste après le champ texte pour valider la recherche..

pour finir, l'application est localisée en anglais, du coup tout est labelisé en anglais en dehors de l'ap. le clavier, la barre du haut de l'écran. par exemple battery power, 3 of 3 barre wifi, network...

**Comment by DVRGV38** [comment]
Utilisateur 2 : Avec VoiceOver, iPhone 4S iOs9

Dans le lecteur audio, aléatoirement, le bouton de lecture est libellé en « Pause ».

**Comment by DVRGV38** [comment]
Utilisateur1 
Erreur de ma part, le champ de recherche n'est pas activé lorsque je lance l'application.

**Comment by DVRGV38** [comment]
Utilisateur 3 : avec iPhone 6,
Graphisme légé mais clair.
J’aurais aimé voir comme fonctionnalités supplémentaire, la possibilité de partager un article sur les réseaux sociaux, de commenter les articles.
Un écran unique pour la présentation et les remerciements.
L’application est un peu sommaire en contenu, j’ai hâte de voir les prochaines versions.

**Comment by DVRGV38** [comment]
Utilisateur4 : Iphone 7 Ios10.0.2 avec VoiceOver
cette app contient des éléments dont le label est incorrect ("Title") ainsi qu'une gestion partielle de la lecture en arrière-plan (impossibilité de mettre le podcast en pause sans devoir nécessairement revenir dans l'app).
En effet, par exemple, lorsqu'on utilise Youtube, ou musique, nous pouvons faire un arrêt de la lecture par un double-tape avec deux doigts.
La désactivation de la mise en veille serait pas mal.

**Comment by DVRGV38** [comment]
Ok pour reporter l'implémentation de la rubrique actualité...
Mais il va falloir bosser sur tous les petits bugs y compris ceux d'accessibilité avec VoiceOver pour la version 1.0.1

**Comment by iLandes** [comment]
C'est assez difficile de gérer les bugs ou les incompréhension comme ça. Le mieux serait d'avoir un fil de discussion par bug et un lien avec les utilisateurs pour pouvoir discuter avec eux. Je vais essayer de faire du tri. A l'avenir, mieux faut utiliser un système de forum qui permet de dialoguer avec les utilisateurs. Je vais redécouvre tout cela.
