### ISSUE TITLE
Onglet Actualités

### ISSUE THREAD

**Issue by DVRGV38** [iLandes/DVRGV-PUBLIC#34]
Pour simplifier le travail, j'ai décidé de créé un flux RSS pour les actualités.
Au sein de la page d'accueil de de Wordpress, j'ai supprimé les articles classés dans la catégories "actualite".
Je ne peux pas faire de teste actuellement pour pas planter l'application mobile, mais à priori, il faudrait faire une requête qui n'inclue pas la catégorie "actualite".
Dans l'onglet "Actualite" qui sera en première position, il faudra faire une récupération du flux rss suivant 
http://test.dvrgv.org/category/actualite/feed/
Ce flux renvoie uniquement les articles de la rubrique actualite
Au final, ce sera casiment la même page que pour les podcasts sans le lecteur audio...

**Comment by iLandes** [comment]
Cette discussion fait suite à une autre fermée sur le même sujet.

Je compte implémenter cette fonction dans une version future. (1.1)

**Comment by iLandes** [comment]
Transférer dans le compte privé
