### ISSUE TITLE
Rubrique Actualité

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#36]
> Le Flux XML renvoie aussi les infos de la rubrique actualité.
> Il faudrait dans la rubrique podcast, faire une requête qui ne prend pas en compte les éléments de la catégorie actualité, et dans un second onglet, faire une requête qui inclus uniquement la catégorie actualité. Les teste sont à faire sur le site de teste

Pour le moment il n'y a pas de balise Actualité dans le flux XML : http://test.dvrgv.org/podcast

**Comment by DVRGV38** [comment]
OK, c’est bon j’ai augmenté le nombre d’élément dans le flux podcast
Si tu ne vois pas les éléments actualité
http://test.dvrgv.org/category=actualite

**Comment by iLandes** [comment]
Je galère avec le nouveau flux XML. Je n’arrive pas a charger tous les items. Je ne reçois que le premier.


J’ai essayé de l’interroger avec VisualXML un petit utilitaire trouvé sur le Mac App Store. Il ne trouve que le premier. Pourtant avec un autre logiciel : Shrookg je reçois bien tous les éléments.

Mystère et boule de gomme

**Comment by DVRGV38** [comment]
En ce qui me concerne, j’interroge le flux xml avec Vienna sur OSX. Et avec Lire su IOS et j’ai tous les éléments…

**Comment by iLandes** [comment]
J’ai trouvé la ligne qui pose problème.

<rawvoice:poster url="http://test.dvrgv.org/PhotosArticles/2016-08-16-FR3AlpesStudio&Camera.jpg <http://test.dvrgv.org/PhotosArticles/2016-08-16-FR3AlpesStudio&Camera.jpg>" />


Ca fait bien deux heures et demi que je cherche.

C’est le & qui pose problème au parser XML. Normalement & s’écrit &amp;

Je pense que dans ton wordpress tu ne nomes pas les images correctement. De mon côté je n’arrive pas à détecter cette erreur (certaine application y arrive) et cela m’énerve un peu car même si tu corriges pour cette fois si on prend le risque que l’erreur se reproduise et fasse planter toute l’application.


s
e
b

**Comment by DVRGV38** [comment]
Ok…
Bah il suffit que je le sache et je mettrai plus de &

Je vais d’ailleurs l’enlever

**Comment by iLandes** [comment]
Comme je n’aime pas laisser un bug connu qui laisse l’application sans information pour l’utilisateur. même s’il ne peut rien y faire je vais prévoir le coup et afficher un message d’erreur lui demandant de nous le signaler.

On refait toujours un jour ou l’autre une erreur que l’on a déjà faites.

Tu as une adresse mail vers laquelle on pourrait dire à l’utilisateur de reporter l’erreur ?

**Comment by DVRGV38** [comment]
Oui je vais créer une adresse spécialement pour cet effet : feedback@dvrgv.org
Je l’a créée dans la soirée

**Comment by iLandes** [comment]
Pour la gestion des actualités, je te propose de mettre cela dans la prochaine version et de rester concentré sur la version actuelle car j'ai déjà passé pas mal de temps sur le debug du fichier XML.

Il faut rapidement sortir une version correcte ;-)

**Comment by iLandes** [comment]
Je laisse ce post ouvert pour que l'on définisse ensemble comment présenté la rubrique actualité. Pour l'instant rien dans le flux XML avec le tag Actualité.

**Comment by iLandes** [comment]
Finalement je clos cette discussion, il y en a une autre plus _propre_ concernant l'onglet actualité.
