### ISSUE TITLE
Utilisateur 1 : Les boutons radios de la zone de recherche sont labelisés title

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#37]
Utilisateur 1: avec VoiceOver sur Iphone SE, iOs10

De mon côté il y a un petit souci, les boutons radios de la zone de recherche sont labelisés title pour les deux, et je ne vois pas de différence entre l'un et l'autre.

De plus le fait que le champ de recherche soit actif par défaut empèche la vue des onglets en bas Impossible de quitter le clavier, un bouton terminer au lieu de rechercher serait peut-être plus aproprié et un bouton de recherche juste après le champ texte pour valider la recherche..

pour finir, l'application est localisée en anglais, du coup tout est labelisé en anglais en dehors de l'ap. le clavier, la barre du haut de l'écran. par exemple battery power, 3 of 3 barre wifi, network...

**Comment by iLandes** [comment]
Je n'ai pas encore fait de test avec iOS 10. 

Cela ressemble à un bug lié à iOS 10. Quel version précise d'iOS10 est utilisé.

En ce qui concerne la barre du haut, le clavier, la barre wifi ce n'est pas géré par l'application. Après il me semble que j'avais un problème de config de l'application qui disait que l'anglais était supporté, cela peut venir de là.

Pour l'instant tant que je n'ai pas fait de test sur iOS 10 et que je ne connais pas la version exacte, je ne peux avancer sur ce sujet.

**Comment by iLandes** [comment]
Utilisateur1 
Erreur de ma part, le champ de recherche n'est pas activé lorsque je lance l'application.

**Comment by iLandes** [comment]
Il me faut plus d'informations…

**Comment by DVRGV38** [comment]
Lorsque je lance l’application, j’arrive bien sur la liste des podcasts et au dessus de la recherche, j’ai deux boutons radio labellisé « Title » et « Title »…
Ça n’a aucun effet lorsque je clique dessus…
Ma femme me dit que ce qu’annonce VoiceOver pour les Title indique le champ de recherche.
Le premier Title est à gauche du champ recherche, et le deuxième est à droite du change recherche.
Visuellement, elle me dit que il n’y a aucun label visible. Elle se repère grâce à VoiceOver qui entoure graphiquement le contrôle qui est en focus...

**Comment by iLandes** [comment]
Toujours d'actualité ? Si oui faire une entrée dans le GitHub privé
