### ISSUE TITLE
Utilisateur 2 : le bouton de lecture est libellé en « Pause »

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#38]
Utilisateur 2 : Avec VoiceOver, iPhone 4S iOs9

Dans le lecteur audio, aléatoirement, le bouton de lecture est libellé en « Pause ».

**Comment by iLandes** [comment]
Cela n'a rien d'anormal. Suivant la connection internet de l'appareil pendant l'utilisation si le cache est insuffisant le player se met en pause.

**Comment by DVRGV38** [comment]
![img_0051](https://cloud.githubusercontent.com/assets/20368237/19386364/0d28d732-9214-11e6-8e0e-d4984699af1f.PNG)
En revanche, j’ai toujours moi aussi ce soucis de Play/pause qui s’affiche aléatoirement…
Je te joins un imprime écran fait après avoir affiché l’article pendant 2 minutes… Je suis en VDSL donc 31,8MO en débit descendant…
Soi, c’est VoiceOver, soi c’est un soucis au niveau du cache…
Ça n’enlève rien à la fonctionnalité ceci dit, je clique sur le bouton labellisé en « Pause » et ça me lance la lecture. Je appuie sur ce bouton labellisé «  pause » et ça s’arrête et là, le bouton se transforme bien en « lecture »

**Comment by iLandes** [comment]
Transférer dans le GitHub privé
