### ISSUE TITLE
Flux Facebook à inclure dans l'app

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#4]
http://www.facebook.com/feeds/page.php?format=rss20&id=1488428061369878

**Comment by DVRGV38** [comment]
Le flux xml pour facebook : http://flux.saynete.net/fbook_dvrgv.xml?id=1488428061369878
Il n'est pas au format https mais ce n'est pas moi qui gère ça... Je crois pas qu'il y ait d'autres moyens de récupérer facebook en xml... A voir !!!

**Comment by DVRGV38** [comment]
Je travaille sur une appli php qui permettra de récupérer le flux xml sur le site, ce qui nous permettra d'afficher cette page dans l'application (onglet actualité)

**Comment by DVRGV38** [comment]
Substitué par mon option avec le flux https://www.dvrgv.org/category/actualite/feed/
Je ne veux pas dépendre de Facebook, ils ont déjà modifié leur api, encore moi d'un autre gars que je ne connais pas qui peut suspendre le flux à n'importes quel moment...
