### ISSUE TITLE
Categorie du Podacst

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#5]
Pour certaines des productions, je ne vois pas la catégorie associée comme par exemple :
« Bonne année DVRGV » qui doit être dans la catégorie « Vie du Site »

**Comment by iLandes** [comment]
Pour la catégorie du podcast je me suis servi dans la balise <itunes:keywords>. Comme je te le disais dans un mail précédant la balise dans le fichier XML, un podcast contient plusieurs balises <Category> qui ressemblent plus à des mot clés. Dans ton exemple pour 'Bonne année DVRGV’ on a les balises <Category> suivante :

			<category>
				Vie Du Site
			</category>
			<category>
				2016
			</category>
			<category>
				Bonne Année
			</category>
			<category>
				Making-Of
			</category>

Le mieux serait alors de changer les données fournis par le XML pour n’avoir qu’une seule catégorie et pourquoi pas plusieurs mot clés par exemple :
		<category>
				Vie Du Site
			</category>
			<keywords>
				2016, Bonne Année, Making-Of
			</keywords >

Ou alors de systématisé la balise <itunes:keywords> qui n’est pas présente dans tous les podcasts.

**Comment by iLandes** [comment]
Dans l’attente de ton retour pour définir la solution à adopter pour récupérer la catégorie d’un podcast. Pour corriger momentanément se problème en l’absence de balise <itunes:keywords> le podcast est classée dans une catégorie « Non classée »

**Comment by DVRGV38** [comment]
De ceuq eut u me dis, il semble que ce soit la première catégorie à prendre en compte, le reste étant des mots clefs. Wordpress ne semble pas dissocié les deux. donc utilise le première catégorie

**Comment by iLandes** [comment]
Ok. Ce n'est pas très logique de la part de WordPress de mettre des catégories les unes à la suite des autres avec la même entête. Je vais me débrouiller avec leur logique tordu qui n'est pas très XML.

**Comment by iLandes** [comment]
Corrigé dans la build 4
