### ISSUE TITLE
Flux en https

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#7]
Pour garantir le niveau de sécurité exigé par Apple, il faut que le flux XML soit en https. Merci de te rapprocher de ton hébergeur

**Comment by DVRGV38** [comment]
La procédure est en cours. Le certificat SSL a été acheté, je travaille à le mettre en place !

**Comment by DVRGV38** [comment]
Voilà...
La migration des données vers le nouveau serveur est terminée.
De plus, le certificat SSL est opérationnel.
La base de donnée a été mise à jour en conséquence...
