### ISSUE TITLE
Avance grâce à la barre de progression du lecteur

### ISSUE THREAD

**Issue by iLandes** [iLandes/DVRGV-PUBLIC#8]

**Comment by iLandes** [comment]
Disponible à partir du build 4

**Comment by DVRGV38** [comment]
Inaccessible avec VoiceOver!

**Comment by iLandes** [comment]
Effectivement, la progression n'est pas accessible quand VoicePver est activé, je vais rajouter deux boutons à côté du bouton lecture par avancer et reculer dans le podcast. Je maintient tout de même cette fonction sur le slider pour les utilisateurs qui n'utilisent pas VoiceOver

**Comment by DVRGV38** [comment]
Très bien, un bouton reculer et avancer, ce qui permet de sauter toutes les 10 secondes par exemple.
Garder la barre de progression malgré tout, c'es très bien aussi, cette application n'étant pas destinée uniquement aux déficients-visuels, donc très bonne initiative...

**Comment by iLandes** [comment]
J'ai intégrer un bouton Avancer et Reculer compatible voice over dans la build 5

**Comment by DVRGV38** [comment]
Dans cette dernière version, je n'ai plus accès à aucun bouton de fonction. ni lecture, ni pause, ni avance, ni recul... Je ne vois que le temps

**Comment by iLandes** [comment]
Les boutons apparaisse une fois que les 5 premières secondes sont chargés

**Comment by DVRGV38** [comment]
Ok, alors il faudrait mettre un message temporaire qui l’indique…
Je travaille sur des petits sons à inclure dans l’application ce qui permettra de donner des informations suplémentaires à l’utilisateur aveugle.

**Comment by iLandes** [comment]
Il y un progressView indicator (C’est une sorte de roue qui tourne), Normalement elle est intégré un UIAccessiblity (voiceOver) mais ce n’est peut-être pas très user Friendly. Effectivement des sons serait pas mal à intégrer et plus facile à intégré pour les utilisateurs

**Comment by DVRGV38** [comment]
ok, je m’en occupe, quel format est plus simple pour toi ?


Amicalement…
Manu

-	E-Mail : etann@manu-dpk.net
-	Skype : manu-dpk
-	Site web : http://www.manu-dpk.net
 	                 http://www.dvrgv.org

__________________________________________Respectons l’environnement, n’imprimez ce message uniquement que si ça vous est nécessaire !

**Comment by iLandes** [comment]
Aucune importance,

Je suis illustrateur sonore, je devrais me débrouiller avec n’importe quel format

s
e
b

**Comment by iLandes** [comment]
Dans la build 7 j'ai ajouter un label "Chargement en cours"
